export const paths = {
  home: "/",
  products: "/products",
  productsByCategory: (category: string) => `/products?category=${encodeURIComponent(category)}`,
  productsByBrand: (brand: string) => `/products?brand=${encodeURIComponent(brand)}`,
  productsByCategoryAndBrand: (category: string, brand: string) => `/products?category=${encodeURIComponent(category)}&brand=${encodeURIComponent(brand)}`,
  productDetail: (slug: string) => `/products/${slug}`,
  aiAdvisor: "/ai-advisor",
  cart: "/cart",
  checkout: "/checkout",
  account: "/account",
  login: "/login",
  register: "/register",
  admin: {
    root: "/admin",
    login: "/admin/login",
    products: "/admin/products",
    categories: "/admin/categories",
    brands: "/admin/brands",
    orders: "/admin/orders",
    users: "/admin/users",
    customers: "/admin/customers",
  },
} as const;
